name: lakos
description: Visualize Dart library dependencies in Graphviz dot. Detect dependency cycles.
version: 1.4.1
homepage: https://github.com/OlegAlexander/lakos

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  lakos:

dependencies:
  path: ^1.8.0
  args: ^2.0.0
  directed_graph: ^0.3.2
  glob: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  pub_cache: ^0.3.0
  string_scanner: ^1.1.0
