name: lakos
description: Visualize internal Dart library dependencies in Graphviz dot. Detect dependency cycles.
version: 2.0.3
homepage: https://github.com/OlegAlexander/lakos

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  lakos:

dependencies:
  path: 1.8.3
  args: 2.3.2
  directed_graph: 0.3.7
  glob: 2.1.1
  darq: 1.2.1

dev_dependencies:
  lints: 2.0.1
  test: 1.22.2
  string_scanner: 1.2.0
  yaml: 3.1.1
  pub_semver: 2.1.3
