name: lakos
description: Visualize internal Dart library dependencies in Graphviz dot. Detect dependency cycles.
version: 2.0.4
homepage: https://github.com/OlegAlexander/lakos

environment:
  sdk: ">=2.12.0 <4.0.0"

executables:
  lakos:

dependencies:
  path: 1.9.0
  args: 2.4.2
  directed_graph: 0.4.0
  glob: 2.1.2
  darq: 2.0.0

dev_dependencies:
  lints: 3.0.0
  test: 1.25.2
  string_scanner: 1.2.0
  yaml: 3.1.2
  pub_semver: 2.1.4
