name: lakos
description: Visualize Dart library dependencies in Graphviz dot.
version: 1.0.0
homepage: https://github.com/OlegAlexander/lakos

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  lakos:

dependencies:
  path: ^1.7.0
  args: ^1.6.0
  directed_graph: ^0.1.8
  glob: ^1.2.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.15.3
  pub_cache: ^0.2.3
  json_serializable: ^3.3.0
  dart_code_metrics: ^1.8.1
  string_scanner: ^1.0.5
