name: lakos
description: Visualize internal Dart library dependencies in Graphviz dot. Detect dependency cycles.
version: 2.0.6
homepage: https://github.com/OlegAlexander/lakos

environment:
  sdk: ">=2.12.0 <4.0.0"

executables:
  lakos:

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  directed_graph: ^0.4.5
  glob: ^2.1.3
  darq: ^2.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  string_scanner: ^1.4.1
  yaml: ^3.1.3
  pub_semver: ^2.2.0
