name: lakos
description: Visualize internal Dart library dependencies in Graphviz dot. Detect dependency cycles.
version: 2.0.2
homepage: https://github.com/OlegAlexander/lakos

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  lakos:

dependencies:
  path: 1.8.1
  args: 2.3.0
  directed_graph: 0.3.6
  glob: 2.0.2
  darq: 1.1.1

dev_dependencies:
  lints: 1.0.1
  test: 1.20.1
  pub_cache: 0.3.1
  string_scanner: 1.1.0
