name: lakos
description: Visualize library dependencies as a dot graph.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  lakos:

dependencies:
  path: 1.7.0
  args: 1.6.0
  package_config: 1.9.3

dev_dependencies:
  pedantic: ^1.8.0
  test: 1.14.2
  pub_cache: 0.2.3
  json_serializable: 3.3.0
  analyzer: 0.39.8
