name: lakos
description: Visualize library dependencies as a dot graph.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  lakos:

dependencies:
  path: 1.7.0
  args: 1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: 1.14.3
  pub_cache: 0.2.3
  json_serializable: 3.3.0
  dart_code_metrics: 1.4.0
