name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install graphviz dot
      run: |
        apt update
        apt install graphviz -y
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
